### ISSUE TITLE
Setting winrm_no_proxy causes timeout

### ISSUE THREAD

**Issue by timwebster9** [hashicorp/packer#10343]
We need to set `winrm_no_proxy` as we are behind a corporate proxy.  Setting this to `true` allows us to connect to our instance private IP, but it also causes it to hang. Let me explain:

Initially with this set to `true`, Packer will encounter the WinRM timeout. However I can see that traffic is reaching the VM from my Azure Firewall logs (or more accurately, is using the private network instead of the proxy).  I can also see that WinRM is correctly configured on the VM if I RDP onto the VM and inspect the WinRM listeners, firewall rules, etc.

After a bunch of troubleshooting, we discovered that if we execute a 'Run Command' from the Azure portal and run this command on the VM: `cmd.exe /c winrm set "winrm/config/service/auth" '@{Basic="true"}'` then Packer will connect. I have no idea why that happens because Packer works fine with that being set to `false` normally.

I initially thought this was an environment issue.  However I can reproduce this same behaviour in my personal Azure tenant (no proxies or firewalls and using a public IP address for the VM).  If I just follow [this guide](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/build-image-with-packer) from Microsoft but insert `winrm_no_proxy: true` into the Packer build file I can reproduce the same behaviour, with the same fix.  It's only when the `winrm_no_proxy` setting is turned on that we have a problem.  I realise that setting `winrm_no_proxy` makes no sense if you're not using a proxy, but this is just to show the issue can be reproduced.

We are using azure-arm builder and trying to build Windows Server 2019 images using Packer 1.6.5.  VM size is `Standard_D2_v2`.

**UPDATE:** I installed a proxy and tried the same experiment to better reflect a real-world scenario, and got the same result.  Although Packer correctly sent the Azure API traffic via the proxy and the WinRM requests directly to the VM IP address, setting `winrm_no_proxy` still results in a WinRM timeout.

**UPDATE 2:** added packer debug log

Build output:
```
==> azure-arm: Getting the VM's IP address ...
==> azure-arm:  -> ResourceGroupName   : 'myPackerGroup'
==> azure-arm:  -> PublicIPAddressName : 'pkripx8yxp97kll'
==> azure-arm:  -> NicName             : 'pkrnix8yxp97kll'
==> azure-arm:  -> Network Connection  : 'PublicEndpoint'
==> azure-arm:  -> IP Address          : '51.140.12.157'
==> azure-arm: Waiting for WinRM to become available...

*** Hangs at this points.  Run cmd.exe /c winrm set "winrm/config/service/auth" '@{Basic="true"}' in Azure Portal using 'Run Command' feature. ***

azure-arm: WinRM connected.
==> azure-arm: #< CLIXML
==> azure-arm: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm: Connected to WinRM!
==> azure-arm: Provisioning with Powershell...
```
Debug log from Packer:
```
2020/12/08 11:03:49 packer-builder-azure-arm plugin: [INFO] Attempting WinRM connection...
2020/12/08 11:03:49 packer-builder-azure-arm plugin: [DEBUG] connecting to remote shell using WinRM
2020/12/08 11:03:50 packer-builder-azure-arm plugin: [ERROR] connection error: http response error: 401 - invalid content type
2020/12/08 11:03:50 packer-builder-azure-arm plugin: [ERROR] WinRM connection err: http response error: 401 - invalid content type
2020/12/08 11:03:55 packer-builder-azure-arm plugin: [INFO] Attempting WinRM connection...
2020/12/08 11:03:55 packer-builder-azure-arm plugin: [DEBUG] connecting to remote shell using WinRM
2020/12/08 11:03:55 packer-builder-azure-arm plugin: [ERROR] connection error: http response error: 401 - invalid content type
2020/12/08 11:03:55 packer-builder-azure-arm plugin: [ERROR] WinRM connection err: http response error: 401 - invalid content type
2020/12/08 11:04:00 packer-builder-azure-arm plugin: [INFO] Attempting WinRM connection...
```

Build template.  Basically [this](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/build-image-with-packer#define-packer-template) with `winrm_no_proxy` added:
```
{
  "builders": [{
    "type": "azure-arm",

    "client_id": "xxxxx-xxxxx-xxxxx-xxxxx",
    "client_secret": "xxxxx",
    "tenant_id": "xxxxx-xxxxx-xxxxx-xxxxx",
    "subscription_id": "xxxxx-xxxxx-xxxxx",

    "managed_image_resource_group_name": "myPackerGroup",
    "managed_image_name": "myPackerImage",

    "os_type": "Windows",
    "image_publisher": "MicrosoftWindowsServer",
    "image_offer": "WindowsServer",
    "image_sku": "2016-Datacenter",

    "communicator": "winrm",
    "winrm_use_ssl": true,
    "winrm_no_proxy": true,
    "winrm_insecure": true,
    "winrm_timeout": "30m",
    "winrm_username": "packer",

    "azure_tags": {
        "dept": "Engineering",
        "task": "Image deployment"
    },

    "build_resource_group_name": "myPackerGroup",
    "vm_size": "Standard_D2_v2"
  }],
  "provisioners": [{
    "type": "powershell",
    "inline": [
      "Add-WindowsFeature Web-Server",
      "while ((Get-Service RdAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
      "while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
      "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
      "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
    ]
  }]
}
```

**Comment by timwebster9** [comment]
Is anyone able to look at this?  It seems as though it is currently not possible to build Windows VMs on Azure if you are behind a proxy.

**Comment by JvanDerPaal** [comment]
getting the same issue. but I'm buil;ding in an isolate vnet with no peering and no proxy, just two VMs.

**Comment by JvanDerPaal** [comment]
@timwebster9 
something else to try and hass worked for my scanario with server 2019.
added image_version, I'm using a November version of the image, from when my code last worked.
this isn't a solution but more a temporary workaround to help diagnose the issue.
Something has changed within the OS to no longer work with packer to get that initial connection.

```
            "os_type": "Windows",
            "image_publisher": "MicrosoftWindowsServer",
            "image_offer": "WindowsServer",
            "image_sku": "2019-Datacenter",
            "communicator": "winrm",
            "winrm_use_ssl": "true",
            "winrm_insecure": "true",
            "winrm_username": "packer",
            "winrm_timeout": "60m",
            "image_version": "17763.1579.2011180054"
```

**Comment by Bourne-ID** [comment]
A change in the base image doesn't explain why the var of winrm_no_proxy would work on one, but not the other - if there was a base change to the image then one would expect it to impact with or without this setting. 

I've been doing some packet capturing and delving into this issue - it appears that when no_proxy is defined, the first wsman connection is including a basic authentication header, which is different to when no_proxy is off as this has no basic auth header. 

It's a small difference but could explain why one fails when the other succeeds - going to dig further to see what I can find out.

**Comment by Bourne-ID** [comment]
Looks like it's a mix of masterZen/winrm and Packer - when no_proxy is omitted/false then the TransportDecorator is NTLM (for my example anyway), which authenticates correctly. When I need to use the no_proxy, this is overridden with a clientRequest when, from my understanding, is removing the NTLM wrappers from firing. 

https://github.com/hashicorp/packer-plugin-sdk/blob/main/communicator/step_connect_winrm.go#L146

With No_Proxy:
![image](https://user-images.githubusercontent.com/7073616/106526495-bd225700-64b3-11eb-9575-9ad7ee930381.png)

Without No_Proxy:
![image](https://user-images.githubusercontent.com/7073616/106526531-cc090980-64b3-11eb-98f1-87cbd095f40d.png)

**Comment by nywilken** [comment]
Thanks for reaching out and for the detailed debug information. We take a look as soon as we can.

**Comment by SwampDragons** [comment]
I made a comment to hopefully bump your PR on the upstream library.

**Comment by stephan9** [comment]
@SwampDragons in which release can we expect the fix to be out? Thanks

**Comment by SwampDragons** [comment]
@stephan9  This has been merged with the packer-plugin-sdk here https://github.com/hashicorp/packer-plugin-sdk/pull/66

This means it will be available as soon as a new release is cut for the plugin you use. Are you experiencing this on Azure, or a different plugin?

**Comment by stephan9** [comment]
@SwampDragons yes my issue is with the azure-arm builder. My use case is creating an Azure Windows 2019 image from an AWS instance with a proxy in between.

Is it the `packer-plugin-azure` repo I should keep an eye on? Since the `builder/azure/arm/builder.go` is importing `github.com/hashicorp/packer-plugin-sdk/communicator` am I right to assume it should work now? Or does the go.mod needs to be updated first? Apologies for my limited Go knowledge.

**Comment by SwampDragons** [comment]
I just cut a new release of the Azure plugin using the latest SDK, so if you install v0.0.3 of https://github.com/hashicorp/packer-plugin-azure it should have support for this.

**Comment by Bourne-ID** [comment]
@SwampDragons Just want to check - this issue being closed means it's confirmed for release 1.7.3? (IE the packer-plugin-sdk will be updated in the next release to contain the fix?)

Many Thanks

**Comment by SwampDragons** [comment]
Yes, but you can download the updated plugin from the plugin's github https://github.com/hashicorp/packer-plugin-azure/releases/tag/v0.0.3 and install it now if you don't want to wait for the 1.7.3 release of Packer.

**Comment by yuanxnab** [comment]
I've manually installed the updated plugin (v0.0.3), but it's still unable to reach WinRM with the `winrm_no_proxy` flag set to `true`.

@Bourne-ID Do you mind sharing the app that you used to trace/view the client payloads in your [screenshots above](https://github.com/hashicorp/packer/issues/10343#issuecomment-771207712). I want to validate whether the updated plugin is correctly setting the TransportDecorator with NTLM or not.
