### ISSUE TITLE
Packer Plugin Oxide: Integration Request

### ISSUE THREAD

**Issue by sudomateo** [hashicorp/packer#13421]
#### Description

The [Oxide](https://oxide.computer/) multi-component plugin can be used with HashiCorp (IBM) Packer to create custom Oxide images.

https://github.com/oxidecomputer/packer-plugin-oxide

#### Integration Tier

Community.

#### Checklist
- [x] Has valid [`metadata.hcl`](https://github.com/hashicorp/integration-template) file in plugin repository.
- [x] Has added integration scripts [packer-plugin-scaffolding](https://github.com/hashicorp/packer-plugin-scoffolding) to plugin repository.
- [x] Has added top-level integration README.md file to plugin `docs` directory.
- [x] All plugins components have one README.md describing their usage.
- [x] Has a fully synced `.web-docs` directory ready for publishing to the integrations portal.

**Comment by sudomateo** [comment]
The only GitHub Actions workflows that might be needed in the upstream Oxide repository are the following.

- https://github.com/hashicorp/packer-plugin-scaffolding/blob/main/.github/workflows/notify-integration-release-via-manual.yaml
- https://github.com/hashicorp/packer-plugin-scaffolding/blob/main/.github/workflows/notify-integration-release-via-tag.yaml

I didn't add them since they haven't been updated for 2 years so I wasn't sure if they were still relevant.

**Comment by JenGoldstrich** [comment]
Hey @sudomateo, I hope you are well friend!

So those workflows are relevant still, the integrations repo is private (for some reason), but the integrations-template repo is public https://github.com/hashicorp/integration-template?tab=readme-ov-file#triggering-releases, in it it calls out that the developer page won't contain your newly onboarded plugin until you run the notify job, this is how you update the developer page if you make significant changes to the plugin (adding new builders for example which won't show up in the docs unless you notify integration release).

I've merged a PR to the private repo to onboard the Oxide plugin, but according to that repo it won't show up until you trigger the release via this integration workflow.  I haven't worked with these workflows before to be honest so I may be missing some context, apologies if I am, can you please pull in those upstream workflows, and execute the notify job manually once.

**Comment by sudomateo** [comment]
Hey @JenGoldstrich! Thank you for the reply! All is well here and I hope all is well with you too.

I'll pull in those workflows, run the job, and report back. I'm hoping to do this tonight but I'm finishing up something so I might have to defer until tomorrow. Either way, I'll move forward with that and report back as soon as possible.

**Comment by sudomateo** [comment]
I added the workflows and created a release. The [tag workflow ran successfully](https://github.com/oxidecomputer/packer-plugin-oxide/actions/runs/16133118606)!

I see the Oxide integration [listed on the Packer integrations website](https://developer.hashicorp.com/packer/integrations/oxidecomputer/oxide). However, I don't see documentation for the builder or data source yet. I'll check in on it tomorrow to allow time for propagation.

**Comment by sudomateo** [comment]
Checking in on this. The [Oxide Packer integration](https://developer.hashicorp.com/packer/integrations/oxidecomputer/oxide) page still does not have documentation for the builder and data source components.

<img width="716" height="531" alt="Image" src="https://github.com/user-attachments/assets/3b00b76d-4fdc-4896-aaec-ee36bf49e431" />

I'm unsure what could be causing this but I'll jot some thoughts down to hopefully help spark an idea.

### Thought 1

Did the job that HashiCorp runs to render and publish documentation on the website fail in some manner that's unknown to me?

### Thought 2

Do the headings and list format in `docs/README.md` matter?

The Oxide Packer plugin uses headings 2 and 3 with components listed under heading 3 without an unordered list.

```md
## Components

### Builders

[`oxide-instance`](/packer/integrations/oxidecomputer/oxide/latest/components/builder/instance)
@include 'component/builder/instance/Builder.mdx'

### Data Sources

[`oxide-image`](/packer/integrations/oxidecomputer/oxide/latest/components/data-source/image)
@include 'component/data-source/image/Datasource.mdx'
```

The DigitalOcean Packer plugin uses headings 3 and 4 with components listed in unordered lists under heading 4.

```md
### Components

#### Builders

- [digitalocean](/packer/integrations/digitalocean/digitalocean/latest/components/builder/digitalocean) - The builder takes a source image, runs any provisioning necessary on the image after launching it, then snapshots it into a reusable image. This reusable image can then be used as the foundation of new servers that are launched within DigitalOcean.

#### Data Sources

- [digitalocean-image](/packer/integrations/digitalocean/digitalocean/latest/components/data-source/digitalocean-image) - The DigitalOcean image data source is used look up the ID of an existing DigitalOcean image for use as a builder source.
```

### Thought 3

Is the [`metadata.hcl`](https://github.com/oxidecomputer/packer-plugin-oxide/blob/main/.web-docs/metadata.hcl) file incorrect in some way? I read the documentation and compared it to other files from other plugins and it looked good to me.

**Comment by sudomateo** [comment]
I ran the notify job again and [the logs](https://github.com/oxidecomputer/packer-plugin-oxide/actions/runs/16149389811/job/45576609486) show the following.

```
    "components": [
      {
        "type": "builder",
        "name": "Oxide Instance",
        "slug": "oxide-instance",
        "readme": null,
        "variable_groups": []
      },
      {
        "type": "data-source",
        "name": "Oxide Image",
        "slug": "oxide-image",
        "readme": null,
        "variable_groups": []
      }
    ]
```

The `readme` being `null` is definitely an issue since other plugins have that as non-null. Going to debug this further. I think the `slug` is off.

**Comment by sudomateo** [comment]
Found it! The `slug` was indeed the issue. Fixed in https://github.com/oxidecomputer/packer-plugin-oxide/pull/38.

**Comment by sudomateo** [comment]
I re-ran the notify workflows for all of the releases starting with the earliest release and finishing with the latest release. The documentation for the previous releases is successfully rendering but the documentation for the latest release isn't. I'll wait for propagation to occur but I think we're all good here and I'll mark this closed! Thank you!
