### ISSUE TITLE
crash - markastemplate vsphere post-processor

### ISSUE THREAD

**Issue by jbrowder2** [hashicorp/packer#5529]
- Packer Version = 1.1.2
- Host platform = CentOS Linux release 7.3.1611 (Core) / kernel = 3.10.0-514.6.2.el7.x86_64
- Debug log and template: https://gist.github.com/jbrowder2/0194bb6cea38cb742a0fab0900385774

**Comment by jbrowder2** [comment]
Just realized this is 1.1.2. Disregard.

**Comment by jbrowder2** [comment]
I was able to get the same crash using 1.1.1 and the same packer template.

**Comment by mwhooker** [comment]
here's the problem https://github.com/hashicorp/packer/blob/fe4d4648e697da9447904d6f19d0ad4a2ea8afe9/post-processor/vsphere-template/step_mark_as_template.go#L48

cc @bugbuilder 

not sure why the source doesn't have `/vmfs/volumes/` in it, but we should check the result of the split before indexing into it to prevent panics

**Comment by bugbuilder** [comment]
I'll take a look this Thursday... looks strange to me, could you share your template? Also it would be great to know the vSphere version and topology.

**Comment by jbrowder2** [comment]
The template is at the bottom of the gist linked. vSphere version 6.5.1. Topology is one datacenter with 3 clusters behind it. Right now we are only caring about one of the clusters.

**Comment by bugbuilder** [comment]
Ty, I'll update my environment to 6.5.1, just a quick question if you try to connect to the ESXi is it possible for you to see /vmfs/volumes path? 

I'll ping you when I start to try to fix this bug.

**Comment by jbrowder2** [comment]
Yes, I can see the /vmfs/volumes/* path.

Thanks!

**Comment by bugbuilder** [comment]
I only have my cellphone ń9  


hn

**Comment by jpescalona** [comment]
I think that the value of artifact.Files() receives the path to the local folder where the image was exported:
https://github.com/hashicorp/packer/blob/fe4d4648e697da9447904d6f19d0ad4a2ea8afe9/post-processor/vsphere-template/post-processor.go#L92

I've just printed the value as follow:
```
	source := ""
	for _, path := range artifact.Files() {
		ui.Message("Artifact: "+path)
		if strings.HasSuffix(path, ".vmx") {
			source = path
			break
		}
	}

```
the value of s.Source is the path were the image was exported in local machine:
```
	ui.Message("Source value: " +s.Source)
	source := strings.Split(s.Source, "/vmfs/volumes/")[1]
```
and check the output: 
https://gist.github.com/jpescalona/0660e26bf3a516754e1596bdd6147cde#file-output-log-L909
https://gist.github.com/jpescalona/0660e26bf3a516754e1596bdd6147cde#file-output-log-L918


Additionally, I cannot understand the process follow to publish the template using this post-processor. As I can read in the code:
1. Find the VM
2. Unregister the VM
3. Unregister previous existing template
4. Register the VM in the requested Folder as Template

Probably it can be easier to follow next steps:
1. Unregister the previous existing template
2. Find the VM
3. Mark as template
4. Move into required folder

I've implemented this under https://github.com/hashicorp/packer/pull/5532

**Comment by bugbuilder** [comment]
@jbrowder2 this bug appears when you're exporting the virtual machine, I'll try to fix this as soon as possible, at the moment you could add the attribute `skip_export` as `true` or remove the attribute `format`.

**Comment by bugbuilder** [comment]
@jbrowder2 I read your log and template but they doesn't look consistent, for example, to have [this log](https://gist.github.com/jbrowder2/0194bb6cea38cb742a0fab0900385774#file-packer-crash-L895) you need the `keep_registered` as true but that attribute its not present in your packer template.

I told you this because you're exported the VM and if you don't use `keep_registered` the builder logic will be [remove the remote VM](https://github.com/hashicorp/packer/blob/master/builder/vmware/iso/step_register.go#L61-L74https://github.com/hashicorp/packer/blob/master/builder/vmware/iso/step_register.go#L61-L74). 

@mwhooker is it possible for a post-processor to access to builder attributes? I need to know if  
`keep_registered` was set as true if someone want to use the post-processor whit the export behavior.

**Comment by bugbuilder** [comment]
@jbrowder2 I fixed this bug in this [repo](https://github.com/bennu/packer/tree/vm-template-with-export-vm), it would be helpful if you could do some testing. 

I'm still thinking how to resolve the `keep_registered` issue before sending the PR.

**Comment by mwhooker** [comment]
> @mwhooker is it possible for a post-processor to access to builder attributes? I need to know if
keep_registered was set as true if someone want to use the post-processor whit the export behavior.

You can use `artifact.State`. You can set the state in the builder and access it from the artifact's State method in the post-processor.

**Comment by jbrowder2** [comment]
@bugbuilder awesome thanks! I will get you feedback today.

**Comment by jbrowder2** [comment]
I've ran a test against the bennu/packer/tree/vm-template-with-export-vm branch and I still get a crash. Here is a gist with the crash.log and template-packer.json contents.

https://gist.github.com/jbrowder2/95bacc8f81a2edac0b0cd047d76cac46

**Comment by bugbuilder** [comment]
Add keep_registered=true to your template and try again.

El 7 nov. 2017 14:55, "Josh Browder" <notifications@github.com> escribió:

I've ran a test against the bennu/packer/tree/vm-template-with-export-vm
branch and I still get a crash. Here is a gist with the crash.log and
template-packer.json contents.

https://gist.github.com/jbrowder2/95bacc8f81a2edac0b0cd047d76cac46

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hashicorp/packer/issues/5529#issuecomment-342566897>,
or mute the thread

**Comment by jbrowder2** [comment]
Oops, of course I left that out. I've ran another attempt with keep_registered=true for real this time. I've updated the gist above with the new crash.log and template-packer.json contents.

**Comment by bugbuilder** [comment]
Looks a little strange, because that line doesnt exist in that branch [step_mark_as_template.go:48](https://github.com/bennu/packer/blob/vm-template-with-export-vm/post-processor/vsphere-template/step_mark_as_template.go#L48), only exists in the [current branch](https://github.com/hashicorp/packer/blob/master/post-processor/vsphere-template/step_mark_as_template.go#L48), probably a compilation issue.

Lets build:

mkdir -p new-foder && cd new-foder
git clone https://github.com/bennu/packer.git
cd packer
git checkout vm-template-with-export-vm
docker run --rm -v $(pwd):/go/src/github.com/hashicorp/packer -w /go/src/github.com/hashicorp/packer -e GOARCH=amd64 -e GOOS=linux -e CGO_ENABLED=0 golang:1.8.3-alpine go build -o bin/packer

**Comment by bugbuilder** [comment]
@jbrowder2 any news??

**Comment by jbrowder2** [comment]
I am dealing with issues with our environment. I unfortunately don't have the build environment containerized yet. We are using a VM for a jenkins slave currently. 

after git cloning and using go build I am getting:

checkpoint.go:8:2: cannot find package "github.com/hashicorp/go-checkpoint" in any of:
	/home/users/bhundven/projects/go/src/github.com/hashicorp/go-checkpoint (from $GOROOT)
	/root/go/src/github.com/hashicorp/go-checkpoint (from $GOPATH)
main.go:18:2: cannot find package "github.com/hashicorp/go-uuid" in any of:
	/home/users/bhundven/projects/go/src/github.com/hashicorp/go-uuid (from $GOROOT)
	/root/go/src/github.com/hashicorp/go-uuid (from $GOPATH)
checkpoint.go:9:2: cannot find package "github.com/hashicorp/packer/command" in any of:
	/home/users/bhundven/projects/go/src/github.com/hashicorp/packer/command (from $GOROOT)
	/root/go/src/github.com/hashicorp/packer/command (from $GOPATH)
checkpoint.go:10:2: cannot find package "github.com/hashicorp/packer/packer" in any of:
	/home/users/bhundven/projects/go/src/github.com/hashicorp/packer/packer (from $GOROOT)
	/root/go/src/github.com/hashicorp/packer/packer (from $GOPATH)
config.go:16:2: cannot find package "github.com/hashicorp/packer/packer/plugin" in any of:
	/home/users/bhundven/projects/go/src/github.com/hashicorp/packer/packer/plugin (from $GOROOT)
	/root/go/src/github.com/hashicorp/packer/packer/plugin (from $GOPATH)
checkpoint.go:11:2: cannot find package "github.com/hashicorp/packer/version" in any of:
	/home/users/bhundven/projects/go/src/github.com/hashicorp/packer/version (from $GOROOT)
	/root/go/src/github.com/hashicorp/packer/version (from $GOPATH)
config.go:17:2: cannot find package "github.com/kardianos/osext" in any of:
	/home/users/bhundven/projects/go/src/github.com/kardianos/osext (from $GOROOT)
	/root/go/src/github.com/kardianos/osext (from $GOPATH)
commands.go:6:2: cannot find package "github.com/mitchellh/cli" in any of:
	/home/users/bhundven/projects/go/src/github.com/mitchellh/cli (from $GOROOT)
	/root/go/src/github.com/mitchellh/cli (from $GOPATH)
main.go:24:2: cannot find package "github.com/mitchellh/panicwrap" in any of:
	/home/users/bhundven/projects/go/src/github.com/mitchellh/panicwrap (from $GOROOT)
	/root/go/src/github.com/mitchellh/panicwrap (from $GOPATH)
main.go:25:2: cannot find package "github.com/mitchellh/prefixedio" in any of:
	/home/users/bhundven/projects/go/src/github.com/mitchellh/prefixedio (from $GOROOT)
	/root/go/src/github.com/mitchellh/prefixedio (from $GOPATH)

any idea?

**Comment by jbrowder2** [comment]
when I look at hashicorp/packer/post-processor/vsphere-template/step_mark_as_template.go line 48 is what you posted above, not whats in the current branch from hashicorp/packer. Then, building the new packer binary with go build I still get this error when making it as a template.

panic: runtime error: index out of range
2017/11/07 15:01:25 packer:
2017/11/07 15:01:25 packer: goroutine 109 [running]:
2017/11/07 15:01:25 packer: github.com/hashicorp/packer/post-processor/vsphere-template.(*stepMarkAsTemplate).Run(0xc42042ce60, 0x30ded60, 0xc420011440, 0x0)
2017/11/07 15:01:25 packer: 	/root/go/src/github.com/hashicorp/packer/post-processor/vsphere-template/step_mark_as_template.go:48 +0x9a9
2017/11/07 15:01:25 packer: github.com/hashicorp/packer/vendor/github.com/mitchellh/multistep.(*BasicRunner).Run(0xc4203e59c0, 0x30ded60, 0xc420011440)
2017/11/07 15:01:25 packer: 	/root/go/src/github.com/hashicorp/packer/vendor/github.com/mitchellh/multistep/basic_runner.go:70 +0x1ee
2017/11/07 15:01:25 packer: github.com/hashicorp/packer/post-processor/vsphere-template.(*PostProcessor).PostProcess(0xc42014e300, 0x30e1ee0, 0xc42042c220, 0x30e3da0, 0xc42042c240, 0x0, 0x0, 0xc420011e00, 0x0, 0x0)
2017/11/07 15:01:25 packer: 	/root/go/src/github.com/hashicorp/packer/post-processor/vsphere-template/post-processor.go:126 +0x5ef
2017/11/07 15:01:25 packer: github.com/hashicorp/packer/packer/rpc.(*PostProcessorServer).PostProcess(0xc4202c8960, 0x1, 0xc420045ef0, 0x0, 0x0)
2017/11/07 15:01:25 packer: 	/root/go/src/github.com/hashicorp/packer/packer/rpc/post_processor.go:83 +0x1a8
2017/11/07 15:01:25 packer: reflect.Value.call(0xc420159320, 0xc4201422e0, 0x13, 0x20551d1, 0x4, 0xc4203bdf20, 0x3, 0x3, 0x0, 0x0, ...)
2017/11/07 15:01:25 packer: 	/home/users/bhundven/projects/go/src/reflect/value.go:434 +0x906
2017/11/07 15:01:25 packer: reflect.Value.Call(0xc420159320, 0xc4201422e0, 0x13, 0xc42002d720, 0x3, 0x3, 0x0, 0x0, 0xc420242ae0)
2017/11/07 15:01:25 packer: 	/home/users/bhundven/projects/go/src/reflect/value.go:302 +0xa4
2017/11/07 15:01:25 packer: net/rpc.(*service).call(0xc420139300, 0xc42013b2c0, 0xc420016f28, 0xc42014b180, 0xc4202c8b80, 0x1ad4960, 0xc420017100, 0x18a, 0x1a0c6a0, 0xc420045ef0, ...)
2017/11/07 15:01:25 packer: 	/home/users/bhundven/projects/go/src/net/rpc/server.go:381 +0x142
2017/11/07 15:01:25 packer: created by net/rpc.(*Server).ServeCodec
2017/11/07 15:01:25 packer: 	/home/users/bhundven/projects/go/src/net/rpc/server.go:475 +0x36b
2017/11/07 15:01:25 Deleting original artifact for build 'CentOS-7-x64'
2017/11/07 15:01:25 /usr/local/bin/packer: plugin process exited

any idea?

**Comment by bugbuilder** [comment]
The easier way to get the correct binary without struggle with the environment is using docker as I shown above.

**Comment by bugbuilder** [comment]
@jbrowder2 
```
1. go get github.com/hashicorp/packer
2. cd $GOPATH/src/github.com/hashicorp/packer/
3. git remote add bennu https://github.com/bennu/packer.git
4. git fetch bennu
5. git checkout vm-template-with-export-vm   
6. go build -o bin/packer .
```

**Comment by jbrowder2** [comment]
Excellent, just like you said using docker fixed it. Once I got it built, it works as expected. No more crash. Thanks folks!
