### ISSUE TITLE
Packer fails after submitting the inital spot request, but instance is created

### ISSUE THREAD

**Issue by venkatramtrichy** [hashicorp/packer#8740]
When using the ebs builder with spot instances, Packer fails after submitting the inital spot request with the error:

```
amazon-ebs: Creating Spot Fleet launch template...
amazon-ebs: Sending spot request ()...
==> amazon-ebs: Error waiting for fleet request (fleet-84363b4e-9653-a982-8e10-0b208dca771b) to become ready:There is no Spot capacity available that matches your request.
```
We are not facing this issue regularly. This issue occurs some time but spot instance is created successfully and packer request is failing.

**Simplified packer build file:**

	{
        "builders": [
		{
			"type": "amazon-ebs",
			"region": "us-west-2",
			"associate_public_ip_address": false,
			"source_ami_filter": {
				"filters": {
					"virtualization-type": "hvm",
					"name": "RHEL-8.0_HVM_BETA-20181113-x86_64-1-Hourly2-GP2",
					"root-device-type": "ebs"					
				},
				"most_recent": true
			},
			"block_duration_minutes": "120",
			"spot_instance_types": ["m4.xlarge", "m4.2xlarge", "c4.xlarge", "c4.2xlarge", "r4.xlarge", "r4.2xlarge", "m3.xlarge"],
    		"spot_price": "auto"
			}
    ]
}

**Operating system details**
RHEL

**Packer Version: 1.4.3

**Comment by nywilken** [comment]
Hi @venkatramtrichy thanks for reaching out. Seeing as it doesn't happen all the time its possible that it is an eventual consistency issue and that Packer needs to wait a little longer; essentially retry if the fleet request is not yet available. We’ll take a look when we get a chance.

Thanks for the simplified build file and log output.

**Comment by venkatramtrichy** [comment]
Packer build version is 1.4.3

**Comment by venkatramtrichy** [comment]
As per https://github.com/hashicorp/packer/issues/8169, if we update the packer version from 1.4.3 to 1.5.0, will it fix the issue?

**Comment by nywilken** [comment]
Hi @venkatramtrichy, I took a look yesterday and was not able to reproduce this issue with the latest release of Packer so I was coming back to ask what version you were using :smile: Thanks for updating the issue. 

Updating to a newer version of Packer, currently at v1.5.4, should fix the issue of spot instances being created after an error occurs. It looks like the fix was released in [Packer v1.4.5](https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#bug-fixes-4) if you find that you are not able to upgrade to Packer 1.5.4 so easily.

I am going to close this issue since it has been addressed in newer versions of Packer. If you find you are still running into issues please feel free to update this issue or open a new one with any additional information you may have. Cheers!

**Comment by ddulic** [comment]
Still an issue with packer `1.5.1` and `1.5.4`

Removing `spot_price` fixes the issue, unsurprisingly. That is the only spot flag that we have enabled, everything else is default.

Packer is running within an `amazonlinux:2` container.

**Comment by SwampDragons** [comment]
Can you please open a new issue with full logs and steps to reproduce?

**Comment by ddulic** [comment]
Sure. Will do so in the coming days after I get confirmation what I can post from the logs 👍
